FROM python:3.12-slim AS base
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/src ./src
COPY manage.py backend/entrypoint.sh ./
RUN useradd --create-home django && chown -R django:django /app
USER django
EXPOSE 8000
ENTRYPOINT ["./entrypoint.sh"]
CMD ["gunicorn", "src.config.wsgi:application", "--bind", "0.0.0.0:8000"]
