FROM python:3.9-slim-buster AS base

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/
COPY entrypoint.sh ./
RUN useradd --create-home django && chown -R django:django /app
USER django
EXPOSE 8000
ENTRYPOINT ["./entrypoint.sh"]
CMD ["gunicorn", "src.config.wsgi:application", "--bind", "0.0.0.0:8000"]
