/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: d2Pfbr6bN5UwJ4ss7Fh3HB

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: d2Pfbr6bN5UwJ4ss7Fh3HB/projectModule

import projectcss from "./plasmic.module.css"; // plasmic-import: d2Pfbr6bN5UwJ4ss7Fh3HB/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
