/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: d2Pfbr6bN5UwJ4ss7Fh3HB

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsrf3U7XB0SO } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Rf3u7x-B0S_o/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsrf3U7XB0SO
});
