// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hive_guard_raft.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_hive_5fguard_5fraft_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_hive_5fguard_5fraft_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_hive_5fguard_5fraft_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_hive_5fguard_5fraft_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_hive_5fguard_5fraft_2eproto;
namespace hiveguard {
class Empty;
struct EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class FenceRequest;
struct FenceRequestDefaultTypeInternal;
extern FenceRequestDefaultTypeInternal _FenceRequest_default_instance_;
class GuardStatus;
struct GuardStatusDefaultTypeInternal;
extern GuardStatusDefaultTypeInternal _GuardStatus_default_instance_;
class NodeId;
struct NodeIdDefaultTypeInternal;
extern NodeIdDefaultTypeInternal _NodeId_default_instance_;
class OpResult;
struct OpResultDefaultTypeInternal;
extern OpResultDefaultTypeInternal _OpResult_default_instance_;
}  // namespace hiveguard
PROTOBUF_NAMESPACE_OPEN
template<> ::hiveguard::Empty* Arena::CreateMaybeMessage<::hiveguard::Empty>(Arena*);
template<> ::hiveguard::FenceRequest* Arena::CreateMaybeMessage<::hiveguard::FenceRequest>(Arena*);
template<> ::hiveguard::GuardStatus* Arena::CreateMaybeMessage<::hiveguard::GuardStatus>(Arena*);
template<> ::hiveguard::NodeId* Arena::CreateMaybeMessage<::hiveguard::NodeId>(Arena*);
template<> ::hiveguard::OpResult* Arena::CreateMaybeMessage<::hiveguard::OpResult>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace hiveguard {

// ===================================================================

class NodeId final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hiveguard.NodeId) */ {
 public:
  inline NodeId() : NodeId(nullptr) {}
  ~NodeId() override;
  explicit PROTOBUF_CONSTEXPR NodeId(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NodeId(const NodeId& from);
  NodeId(NodeId&& from) noexcept
    : NodeId() {
    *this = ::std::move(from);
  }

  inline NodeId& operator=(const NodeId& from) {
    CopyFrom(from);
    return *this;
  }
  inline NodeId& operator=(NodeId&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NodeId& default_instance() {
    return *internal_default_instance();
  }
  static inline const NodeId* internal_default_instance() {
    return reinterpret_cast<const NodeId*>(
               &_NodeId_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NodeId& a, NodeId& b) {
    a.Swap(&b);
  }
  inline void Swap(NodeId* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NodeId* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NodeId* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NodeId>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NodeId& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NodeId& from) {
    NodeId::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NodeId* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hiveguard.NodeId";
  }
  protected:
  explicit NodeId(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 1,
  };
  // string node_id = 1;
  void clear_node_id();
  const std::string& node_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_node_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_node_id();
  PROTOBUF_NODISCARD std::string* release_node_id();
  void set_allocated_node_id(std::string* node_id);
  private:
  const std::string& _internal_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(const std::string& value);
  std::string* _internal_mutable_node_id();
  public:

  // @@protoc_insertion_point(class_scope:hiveguard.NodeId)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hive_5fguard_5fraft_2eproto;
};
// -------------------------------------------------------------------

class Empty final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:hiveguard.Empty) */ {
 public:
  inline Empty() : Empty(nullptr) {}
  explicit PROTOBUF_CONSTEXPR Empty(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Empty(const Empty& from);
  Empty(Empty&& from) noexcept
    : Empty() {
    *this = ::std::move(from);
  }

  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }
  inline Empty& operator=(Empty&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Empty& default_instance() {
    return *internal_default_instance();
  }
  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
               &_Empty_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Empty& a, Empty& b) {
    a.Swap(&b);
  }
  inline void Swap(Empty* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Empty* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Empty* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Empty>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Empty& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Empty& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hiveguard.Empty";
  }
  protected:
  explicit Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:hiveguard.Empty)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_hive_5fguard_5fraft_2eproto;
};
// -------------------------------------------------------------------

class GuardStatus final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hiveguard.GuardStatus) */ {
 public:
  inline GuardStatus() : GuardStatus(nullptr) {}
  ~GuardStatus() override;
  explicit PROTOBUF_CONSTEXPR GuardStatus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GuardStatus(const GuardStatus& from);
  GuardStatus(GuardStatus&& from) noexcept
    : GuardStatus() {
    *this = ::std::move(from);
  }

  inline GuardStatus& operator=(const GuardStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline GuardStatus& operator=(GuardStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GuardStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const GuardStatus* internal_default_instance() {
    return reinterpret_cast<const GuardStatus*>(
               &_GuardStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GuardStatus& a, GuardStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(GuardStatus* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GuardStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GuardStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GuardStatus>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GuardStatus& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GuardStatus& from) {
    GuardStatus::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GuardStatus* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hiveguard.GuardStatus";
  }
  protected:
  explicit GuardStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClusterEpochFieldNumber = 1,
    kNodeEpochFieldNumber = 2,
    kIsLeaderFieldNumber = 3,
    kFencedFieldNumber = 4,
  };
  // uint64 cluster_epoch = 1;
  void clear_cluster_epoch();
  uint64_t cluster_epoch() const;
  void set_cluster_epoch(uint64_t value);
  private:
  uint64_t _internal_cluster_epoch() const;
  void _internal_set_cluster_epoch(uint64_t value);
  public:

  // uint64 node_epoch = 2;
  void clear_node_epoch();
  uint64_t node_epoch() const;
  void set_node_epoch(uint64_t value);
  private:
  uint64_t _internal_node_epoch() const;
  void _internal_set_node_epoch(uint64_t value);
  public:

  // bool is_leader = 3;
  void clear_is_leader();
  bool is_leader() const;
  void set_is_leader(bool value);
  private:
  bool _internal_is_leader() const;
  void _internal_set_is_leader(bool value);
  public:

  // bool fenced = 4;
  void clear_fenced();
  bool fenced() const;
  void set_fenced(bool value);
  private:
  bool _internal_fenced() const;
  void _internal_set_fenced(bool value);
  public:

  // @@protoc_insertion_point(class_scope:hiveguard.GuardStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t cluster_epoch_;
    uint64_t node_epoch_;
    bool is_leader_;
    bool fenced_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hive_5fguard_5fraft_2eproto;
};
// -------------------------------------------------------------------

class FenceRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hiveguard.FenceRequest) */ {
 public:
  inline FenceRequest() : FenceRequest(nullptr) {}
  ~FenceRequest() override;
  explicit PROTOBUF_CONSTEXPR FenceRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FenceRequest(const FenceRequest& from);
  FenceRequest(FenceRequest&& from) noexcept
    : FenceRequest() {
    *this = ::std::move(from);
  }

  inline FenceRequest& operator=(const FenceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FenceRequest& operator=(FenceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FenceRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const FenceRequest* internal_default_instance() {
    return reinterpret_cast<const FenceRequest*>(
               &_FenceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(FenceRequest& a, FenceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FenceRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FenceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FenceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FenceRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FenceRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FenceRequest& from) {
    FenceRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FenceRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hiveguard.FenceRequest";
  }
  protected:
  explicit FenceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetNodeIdFieldNumber = 1,
    kFencedFieldNumber = 2,
  };
  // string target_node_id = 1;
  void clear_target_node_id();
  const std::string& target_node_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_target_node_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_target_node_id();
  PROTOBUF_NODISCARD std::string* release_target_node_id();
  void set_allocated_target_node_id(std::string* target_node_id);
  private:
  const std::string& _internal_target_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_target_node_id(const std::string& value);
  std::string* _internal_mutable_target_node_id();
  public:

  // bool fenced = 2;
  void clear_fenced();
  bool fenced() const;
  void set_fenced(bool value);
  private:
  bool _internal_fenced() const;
  void _internal_set_fenced(bool value);
  public:

  // @@protoc_insertion_point(class_scope:hiveguard.FenceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr target_node_id_;
    bool fenced_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hive_5fguard_5fraft_2eproto;
};
// -------------------------------------------------------------------

class OpResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hiveguard.OpResult) */ {
 public:
  inline OpResult() : OpResult(nullptr) {}
  ~OpResult() override;
  explicit PROTOBUF_CONSTEXPR OpResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OpResult(const OpResult& from);
  OpResult(OpResult&& from) noexcept
    : OpResult() {
    *this = ::std::move(from);
  }

  inline OpResult& operator=(const OpResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline OpResult& operator=(OpResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OpResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const OpResult* internal_default_instance() {
    return reinterpret_cast<const OpResult*>(
               &_OpResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(OpResult& a, OpResult& b) {
    a.Swap(&b);
  }
  inline void Swap(OpResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OpResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OpResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OpResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OpResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OpResult& from) {
    OpResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OpResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hiveguard.OpResult";
  }
  protected:
  explicit OpResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMsgFieldNumber = 2,
    kOkFieldNumber = 1,
  };
  // string error_msg = 2;
  void clear_error_msg();
  const std::string& error_msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_msg();
  PROTOBUF_NODISCARD std::string* release_error_msg();
  void set_allocated_error_msg(std::string* error_msg);
  private:
  const std::string& _internal_error_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_msg(const std::string& value);
  std::string* _internal_mutable_error_msg();
  public:

  // bool ok = 1;
  void clear_ok();
  bool ok() const;
  void set_ok(bool value);
  private:
  bool _internal_ok() const;
  void _internal_set_ok(bool value);
  public:

  // @@protoc_insertion_point(class_scope:hiveguard.OpResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_msg_;
    bool ok_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hive_5fguard_5fraft_2eproto;
};
// ===================================================================

class HiveGuardService_Stub;

class HiveGuardService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline HiveGuardService() {};
 public:
  virtual ~HiveGuardService();

  typedef HiveGuardService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void GetStatus(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::hiveguard::Empty* request,
                       ::hiveguard::GuardStatus* response,
                       ::google::protobuf::Closure* done);
  virtual void FenceNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::hiveguard::FenceRequest* request,
                       ::hiveguard::OpResult* response,
                       ::google::protobuf::Closure* done);
  virtual void BumpClusterEpoch(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::hiveguard::Empty* request,
                       ::hiveguard::OpResult* response,
                       ::google::protobuf::Closure* done);
  virtual void BumpNodeEpoch(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::hiveguard::NodeId* request,
                       ::hiveguard::OpResult* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(HiveGuardService);
};

class HiveGuardService_Stub : public HiveGuardService {
 public:
  HiveGuardService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  HiveGuardService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~HiveGuardService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements HiveGuardService ------------------------------------------

  void GetStatus(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::hiveguard::Empty* request,
                       ::hiveguard::GuardStatus* response,
                       ::google::protobuf::Closure* done);
  void FenceNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::hiveguard::FenceRequest* request,
                       ::hiveguard::OpResult* response,
                       ::google::protobuf::Closure* done);
  void BumpClusterEpoch(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::hiveguard::Empty* request,
                       ::hiveguard::OpResult* response,
                       ::google::protobuf::Closure* done);
  void BumpNodeEpoch(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::hiveguard::NodeId* request,
                       ::hiveguard::OpResult* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(HiveGuardService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NodeId

// string node_id = 1;
inline void NodeId::clear_node_id() {
  _impl_.node_id_.ClearToEmpty();
}
inline const std::string& NodeId::node_id() const {
  // @@protoc_insertion_point(field_get:hiveguard.NodeId.node_id)
  return _internal_node_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void NodeId::set_node_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.node_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hiveguard.NodeId.node_id)
}
inline std::string* NodeId::mutable_node_id() {
  std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:hiveguard.NodeId.node_id)
  return _s;
}
inline const std::string& NodeId::_internal_node_id() const {
  return _impl_.node_id_.Get();
}
inline void NodeId::_internal_set_node_id(const std::string& value) {
  
  _impl_.node_id_.Set(value, GetArenaForAllocation());
}
inline std::string* NodeId::_internal_mutable_node_id() {
  
  return _impl_.node_id_.Mutable(GetArenaForAllocation());
}
inline std::string* NodeId::release_node_id() {
  // @@protoc_insertion_point(field_release:hiveguard.NodeId.node_id)
  return _impl_.node_id_.Release();
}
inline void NodeId::set_allocated_node_id(std::string* node_id) {
  if (node_id != nullptr) {
    
  } else {
    
  }
  _impl_.node_id_.SetAllocated(node_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.node_id_.IsDefault()) {
    _impl_.node_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hiveguard.NodeId.node_id)
}

// -------------------------------------------------------------------

// Empty

// -------------------------------------------------------------------

// GuardStatus

// uint64 cluster_epoch = 1;
inline void GuardStatus::clear_cluster_epoch() {
  _impl_.cluster_epoch_ = uint64_t{0u};
}
inline uint64_t GuardStatus::_internal_cluster_epoch() const {
  return _impl_.cluster_epoch_;
}
inline uint64_t GuardStatus::cluster_epoch() const {
  // @@protoc_insertion_point(field_get:hiveguard.GuardStatus.cluster_epoch)
  return _internal_cluster_epoch();
}
inline void GuardStatus::_internal_set_cluster_epoch(uint64_t value) {
  
  _impl_.cluster_epoch_ = value;
}
inline void GuardStatus::set_cluster_epoch(uint64_t value) {
  _internal_set_cluster_epoch(value);
  // @@protoc_insertion_point(field_set:hiveguard.GuardStatus.cluster_epoch)
}

// uint64 node_epoch = 2;
inline void GuardStatus::clear_node_epoch() {
  _impl_.node_epoch_ = uint64_t{0u};
}
inline uint64_t GuardStatus::_internal_node_epoch() const {
  return _impl_.node_epoch_;
}
inline uint64_t GuardStatus::node_epoch() const {
  // @@protoc_insertion_point(field_get:hiveguard.GuardStatus.node_epoch)
  return _internal_node_epoch();
}
inline void GuardStatus::_internal_set_node_epoch(uint64_t value) {
  
  _impl_.node_epoch_ = value;
}
inline void GuardStatus::set_node_epoch(uint64_t value) {
  _internal_set_node_epoch(value);
  // @@protoc_insertion_point(field_set:hiveguard.GuardStatus.node_epoch)
}

// bool is_leader = 3;
inline void GuardStatus::clear_is_leader() {
  _impl_.is_leader_ = false;
}
inline bool GuardStatus::_internal_is_leader() const {
  return _impl_.is_leader_;
}
inline bool GuardStatus::is_leader() const {
  // @@protoc_insertion_point(field_get:hiveguard.GuardStatus.is_leader)
  return _internal_is_leader();
}
inline void GuardStatus::_internal_set_is_leader(bool value) {
  
  _impl_.is_leader_ = value;
}
inline void GuardStatus::set_is_leader(bool value) {
  _internal_set_is_leader(value);
  // @@protoc_insertion_point(field_set:hiveguard.GuardStatus.is_leader)
}

// bool fenced = 4;
inline void GuardStatus::clear_fenced() {
  _impl_.fenced_ = false;
}
inline bool GuardStatus::_internal_fenced() const {
  return _impl_.fenced_;
}
inline bool GuardStatus::fenced() const {
  // @@protoc_insertion_point(field_get:hiveguard.GuardStatus.fenced)
  return _internal_fenced();
}
inline void GuardStatus::_internal_set_fenced(bool value) {
  
  _impl_.fenced_ = value;
}
inline void GuardStatus::set_fenced(bool value) {
  _internal_set_fenced(value);
  // @@protoc_insertion_point(field_set:hiveguard.GuardStatus.fenced)
}

// -------------------------------------------------------------------

// FenceRequest

// string target_node_id = 1;
inline void FenceRequest::clear_target_node_id() {
  _impl_.target_node_id_.ClearToEmpty();
}
inline const std::string& FenceRequest::target_node_id() const {
  // @@protoc_insertion_point(field_get:hiveguard.FenceRequest.target_node_id)
  return _internal_target_node_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FenceRequest::set_target_node_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.target_node_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hiveguard.FenceRequest.target_node_id)
}
inline std::string* FenceRequest::mutable_target_node_id() {
  std::string* _s = _internal_mutable_target_node_id();
  // @@protoc_insertion_point(field_mutable:hiveguard.FenceRequest.target_node_id)
  return _s;
}
inline const std::string& FenceRequest::_internal_target_node_id() const {
  return _impl_.target_node_id_.Get();
}
inline void FenceRequest::_internal_set_target_node_id(const std::string& value) {
  
  _impl_.target_node_id_.Set(value, GetArenaForAllocation());
}
inline std::string* FenceRequest::_internal_mutable_target_node_id() {
  
  return _impl_.target_node_id_.Mutable(GetArenaForAllocation());
}
inline std::string* FenceRequest::release_target_node_id() {
  // @@protoc_insertion_point(field_release:hiveguard.FenceRequest.target_node_id)
  return _impl_.target_node_id_.Release();
}
inline void FenceRequest::set_allocated_target_node_id(std::string* target_node_id) {
  if (target_node_id != nullptr) {
    
  } else {
    
  }
  _impl_.target_node_id_.SetAllocated(target_node_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.target_node_id_.IsDefault()) {
    _impl_.target_node_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hiveguard.FenceRequest.target_node_id)
}

// bool fenced = 2;
inline void FenceRequest::clear_fenced() {
  _impl_.fenced_ = false;
}
inline bool FenceRequest::_internal_fenced() const {
  return _impl_.fenced_;
}
inline bool FenceRequest::fenced() const {
  // @@protoc_insertion_point(field_get:hiveguard.FenceRequest.fenced)
  return _internal_fenced();
}
inline void FenceRequest::_internal_set_fenced(bool value) {
  
  _impl_.fenced_ = value;
}
inline void FenceRequest::set_fenced(bool value) {
  _internal_set_fenced(value);
  // @@protoc_insertion_point(field_set:hiveguard.FenceRequest.fenced)
}

// -------------------------------------------------------------------

// OpResult

// bool ok = 1;
inline void OpResult::clear_ok() {
  _impl_.ok_ = false;
}
inline bool OpResult::_internal_ok() const {
  return _impl_.ok_;
}
inline bool OpResult::ok() const {
  // @@protoc_insertion_point(field_get:hiveguard.OpResult.ok)
  return _internal_ok();
}
inline void OpResult::_internal_set_ok(bool value) {
  
  _impl_.ok_ = value;
}
inline void OpResult::set_ok(bool value) {
  _internal_set_ok(value);
  // @@protoc_insertion_point(field_set:hiveguard.OpResult.ok)
}

// string error_msg = 2;
inline void OpResult::clear_error_msg() {
  _impl_.error_msg_.ClearToEmpty();
}
inline const std::string& OpResult::error_msg() const {
  // @@protoc_insertion_point(field_get:hiveguard.OpResult.error_msg)
  return _internal_error_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OpResult::set_error_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hiveguard.OpResult.error_msg)
}
inline std::string* OpResult::mutable_error_msg() {
  std::string* _s = _internal_mutable_error_msg();
  // @@protoc_insertion_point(field_mutable:hiveguard.OpResult.error_msg)
  return _s;
}
inline const std::string& OpResult::_internal_error_msg() const {
  return _impl_.error_msg_.Get();
}
inline void OpResult::_internal_set_error_msg(const std::string& value) {
  
  _impl_.error_msg_.Set(value, GetArenaForAllocation());
}
inline std::string* OpResult::_internal_mutable_error_msg() {
  
  return _impl_.error_msg_.Mutable(GetArenaForAllocation());
}
inline std::string* OpResult::release_error_msg() {
  // @@protoc_insertion_point(field_release:hiveguard.OpResult.error_msg)
  return _impl_.error_msg_.Release();
}
inline void OpResult::set_allocated_error_msg(std::string* error_msg) {
  if (error_msg != nullptr) {
    
  } else {
    
  }
  _impl_.error_msg_.SetAllocated(error_msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_msg_.IsDefault()) {
    _impl_.error_msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hiveguard.OpResult.error_msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace hiveguard

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_hive_5fguard_5fraft_2eproto
