/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: c8gT28iq7v39gxBJ6CcbGP
// Component: PylZ-UK7gSPz

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import TextField from "../../TextField"; // plasmic-import: OfVdG6fCBlg2/component
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { RichTable } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { tableHelpers as RichTable_Helpers } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { AntdDirectoryTree } from "@plasmicpkgs/antd5/skinny/registerTree";
import { treeHelpers as AntdDirectoryTree_Helpers } from "@plasmicpkgs/antd5/skinny/registerTree";
import { AntdSelect } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: c8gT28iq7v39gxBJ6CcbGP/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: c8gT28iq7v39gxBJ6CcbGP/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: c8gT28iq7v39gxBJ6CcbGP/projectcss
import sty from "./PlasmicDashboard.module.css"; // plasmic-import: PylZ-UK7gSPz/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 1y_RXGc1d4jh/icon

createPlasmicElementProxy;

export type PlasmicDashboard__VariantMembers = {};
export type PlasmicDashboard__VariantsArgs = {};
type VariantPropType = keyof PlasmicDashboard__VariantsArgs;
export const PlasmicDashboard__VariantProps = new Array<VariantPropType>();

export type PlasmicDashboard__ArgsType = {};
type ArgPropType = keyof PlasmicDashboard__ArgsType;
export const PlasmicDashboard__ArgProps = new Array<ArgPropType>();

export type PlasmicDashboard__OverridesType = {
  dashboard?: Flex__<"div">;
  textField?: Flex__<typeof TextField>;
  svg?: Flex__<"svg">;
  table?: Flex__<typeof RichTable>;
  directoryTree?: Flex__<typeof AntdDirectoryTree>;
  select?: Flex__<typeof AntdSelect>;
};

export interface DefaultDashboardProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDashboard__RenderFunc(props: {
  variants: PlasmicDashboard__VariantsArgs;
  args: PlasmicDashboard__ArgsType;
  overrides: PlasmicDashboard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "directoryTree.checkedKeys",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec(
          "checkedKeys",
          AntdDirectoryTree_Helpers
        )
      },
      {
        path: "directoryTree.checkedNodes",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [],

        onMutate: generateOnMutateForSpec(
          "checkedNodes",
          AntdDirectoryTree_Helpers
        )
      },
      {
        path: "directoryTree.checkedDetails",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => ({
          checkedNodesPositions: [],
          halfCheckedKeys: []
        }),

        onMutate: generateOnMutateForSpec(
          "checkedDetails",
          AntdDirectoryTree_Helpers
        )
      },
      {
        path: "directoryTree.selectedKeys",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec(
          "selectedKeys",
          AntdDirectoryTree_Helpers
        )
      },
      {
        path: "directoryTree.selectedNodes",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [],

        onMutate: generateOnMutateForSpec(
          "selectedNodes",
          AntdDirectoryTree_Helpers
        )
      },
      {
        path: "directoryTree.expandedKeys",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec(
          "expandedKeys",
          AntdDirectoryTree_Helpers
        )
      },
      {
        path: "textField.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "table.selectedRowKey",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRowKey", RichTable_Helpers)
      },
      {
        path: "table.selectedRow",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRow", RichTable_Helpers)
      },
      {
        path: "table.selectedRows",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRows", RichTable_Helpers)
      },
      {
        path: "table.selectedRowKeys",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRowKeys", RichTable_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    totalUsersByMonthCustomRange: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "677646ae-cf34-488b-b206-34a10994cc83",
        userArgs: {
          query: [$state.start.value]
        },
        cacheKey: `plasmic.$.677646ae-cf34-488b-b206-34a10994cc83.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    totalOrdersByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "b264dc17-b566-4df0-83a2-ab9388183165",
        userArgs: {
          query: [$state.start.value, $state.start.value]
        },
        cacheKey: `plasmic.$.b264dc17-b566-4df0-83a2-ab9388183165.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    currentRevenue: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "f3936a30-8785-49d2-a5ff-e533ea73d961",
        userArgs: {
          query: [$state.start.value, $state.start.value]
        },
        cacheKey: `plasmic.$.f3936a30-8785-49d2-a5ff-e533ea73d961.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    currentTotalCustomers: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "dcb524d7-464b-4c79-bf25-1565b6400786",
        userArgs: {},
        cacheKey: `plasmic.$.dcb524d7-464b-4c79-bf25-1565b6400786.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    _12MonthRevenue: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "f53b1060-4fb6-42f8-88d1-ee4226cd97a3",
        userArgs: {
          query: [$state.start.value]
        },
        cacheKey: `plasmic.$.f53b1060-4fb6-42f8-88d1-ee4226cd97a3.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    moMUserGrowth: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "7e51db6e-00e4-4875-a459-8ba3f10b6948",
        userArgs: {
          query: [
            $state.start.value,

            $state.start.value,

            $state.start.value,

            $state.start.value
          ]
        },
        cacheKey: `plasmic.$.7e51db6e-00e4-4875-a459-8ba3f10b6948.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    moMOrderGrowth: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "94811363-b732-4daa-b535-1fa376c4b8d6",
        userArgs: {
          query: [
            $state.start.value,

            $state.start.value,

            $state.start.value,

            $state.start.value
          ]
        },
        cacheKey: `plasmic.$.94811363-b732-4daa-b535-1fa376c4b8d6.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    moMAvgOrderGrowth: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "798b2a5a-6de0-46e3-9eec-151c3eae3d7c",
        userArgs: {
          query: [
            $state.start.value,

            $state.start.value,

            $state.start.value,

            $state.start.value
          ]
        },
        cacheKey: `plasmic.$.798b2a5a-6de0-46e3-9eec-151c3eae3d7c.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    moMRevenueGrowth: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "5163246d-39cd-4028-b386-14704292e23b",
        userArgs: {
          query: [
            $state.start.value,

            $state.start.value,

            $state.start.value,

            $state.start.value
          ]
        },
        cacheKey: `plasmic.$.5163246d-39cd-4028-b386-14704292e23b.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    currentAvgOrder: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "bd5d448d-2ef9-48d6-b53b-338a537e93c1",
        userArgs: {
          query: [$state.start.value, $state.start.value]
        },
        cacheKey: `plasmic.$.bd5d448d-2ef9-48d6-b53b-338a537e93c1.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    topCountriesByRevenue: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "1c2b498d-688c-4bb0-8aea-9db5ccb9d052",
        userArgs: {},
        cacheKey: `plasmic.$.1c2b498d-688c-4bb0-8aea-9db5ccb9d052.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    topProductsByQuantitySold: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "667cf2da-35c3-4d28-aebb-2cc54fde4394",
        userArgs: {
          query: [$state.start.value, $state.start.value]
        },
        cacheKey: `plasmic.$.667cf2da-35c3-4d28-aebb-2cc54fde4394.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    totalProductsSold: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "7ad34511-f176-4bf8-b44e-da14621e75fe",
        userArgs: {},
        cacheKey: `plasmic.$.7ad34511-f176-4bf8-b44e-da14621e75fe.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    topCategoriesByOrders: usePlasmicDataOp(() => {
      return {
        sourceId: "mnVdpedBCHqQTtLdFhEqBS",
        opId: "dadf63f0-2634-4ed6-b43f-43e7fcfe4a98",
        userArgs: {
          query: [
            $state.start.value,

            $state.start.value,

            $state.start.value,

            $state.start.value
          ]
        },
        cacheKey: `plasmic.$.dadf63f0-2634-4ed6-b43f-43e7fcfe4a98.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicDashboard.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicDashboard.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicDashboard.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"dashboard"}
          data-plasmic-override={overrides.dashboard}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.dashboard
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox___7XcWx)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__tqu9N)}
              displayHeight={"38px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hive_admin/images/image11.svg",
                fullWidth: 150,
                fullHeight: 150,
                aspectRatio: 1
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__rKQy0)}
              displayHeight={"38px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hive_admin/images/image12.svg",
                fullWidth: 150,
                fullHeight: 150,
                aspectRatio: 1
              }}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__apFbP)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__uyofo)}
              displayHeight={"38px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hive_admin/images/image11.svg",
                fullWidth: 150,
                fullHeight: 150,
                aspectRatio: 1
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__hjl0D)}
              displayHeight={"38px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hive_admin/images/image15.svg",
                fullWidth: 150,
                fullHeight: 150,
                aspectRatio: 1
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__kKm5Q)}
              displayHeight={"38px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hive_admin/images/image15.svg",
                fullWidth: 150,
                fullHeight: 150,
                aspectRatio: 1
              }}
            />

            <TextField
              data-plasmic-name={"textField"}
              data-plasmic-override={overrides.textField}
              className={classNames("__wab_instance", sty.textField)}
              inputMode={"search"}
              label={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kz21U
                  )}
                >
                  {"Label"}
                </div>
              }
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["textField", "value"]).apply(
                  null,
                  eventArgs
                );

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Search"}
              type={"search"}
              value={generateStateValueProp($state, ["textField", "value"])}
            />

            <CircleIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />

            <AntdButton
              className={classNames("__wab_instance", sty.button___0Ex9N)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ak21
                )}
              >
                {"Dashboards"}
              </div>
            </AntdButton>
            <AntdButton
              className={classNames("__wab_instance", sty.button__wqkTh)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__h9OZ9
                )}
              >
                {"Actions"}
              </div>
            </AntdButton>
            <AntdButton
              className={classNames("__wab_instance", sty.button__gpy4Q)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__umVcf
                )}
              >
                {"Logs"}
              </div>
            </AntdButton>
            <AntdButton
              className={classNames("__wab_instance", sty.button___6TTuu)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rps2Z
                )}
              >
                {"Reports"}
              </div>
            </AntdButton>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__i3Qsa)}>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__zSb2D
              )}
              component={Link}
              href={"https://www.plasmic.app/"}
              platform={"nextjs"}
            >
              {"Files"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link___8KqsW
              )}
              component={Link}
              href={"https://www.plasmic.app/"}
              platform={"nextjs"}
            >
              {"Hosts"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__g4Kar
              )}
              component={Link}
              href={"https://www.plasmic.app/"}
              platform={"nextjs"}
            >
              {"Solitaries"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__xLp8N
              )}
              component={Link}
              href={"https://www.plasmic.app/"}
              platform={"nextjs"}
            >
              {"Tennants"}
            </PlasmicLink__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__oRyBh)}>
            {(() => {
              const child$Props = {
                canSelectRows: "click",
                className: classNames("__wab_instance", sty.table),
                onRowSelectionChanged: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "selectedRowKey",
                    ["table", "selectedRowKey"],
                    RichTable_Helpers
                  ).apply(null, eventArgs);
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "selectedRow",
                    ["table", "selectedRow"],
                    RichTable_Helpers
                  ).apply(null, eventArgs);
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "selectedRows",
                    ["table", "selectedRows"],
                    RichTable_Helpers
                  ).apply(null, eventArgs);
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "selectedRowKeys",
                    ["table", "selectedRowKeys"],
                    RichTable_Helpers
                  ).apply(null, eventArgs);
                },
                scopeClassName: sty["table__instance"],
                selectedRowKey: generateStateValueProp($state, [
                  "table",
                  "selectedRowKey"
                ]),
                selectedRowKeys: generateStateValueProp($state, [
                  "table",
                  "selectedRowKeys"
                ]),
                themeResetClassName: classNames(
                  projectcss.root_reset,
                  projectcss.root_reset_tags,
                  projectcss.plasmic_default_styles,
                  projectcss.plasmic_mixins,
                  styleTokensClassNames
                )
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "selectedRowKey",
                    plasmicStateName: "table.selectedRowKey"
                  },
                  {
                    name: "selectedRow",
                    plasmicStateName: "table.selectedRow"
                  },
                  {
                    name: "selectedRows",
                    plasmicStateName: "table.selectedRows"
                  },
                  {
                    name: "selectedRowKeys",
                    plasmicStateName: "table.selectedRowKeys"
                  }
                ],
                [],
                RichTable_Helpers ?? {},
                child$Props
              );

              return (
                <RichTable
                  data-plasmic-name={"table"}
                  data-plasmic-override={overrides.table}
                  {...child$Props}
                />
              );
            })()}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__apTkU)} />

          <div className={classNames(projectcss.all, sty.freeBox__lg0Jy)}>
            {(() => {
              const child$Props = {
                autoExpandParent: true,
                checkable: false,
                checkedKeys: generateStateValueProp($state, [
                  "directoryTree",
                  "checkedKeys"
                ]),
                className: classNames("__wab_instance", sty.directoryTree),
                defaultExpandAll: true,
                expandedKeys: generateStateValueProp($state, [
                  "directoryTree",
                  "expandedKeys"
                ]),
                onCheck: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "checkedKeys",
                    ["directoryTree", "checkedKeys"],
                    AntdDirectoryTree_Helpers
                  ).apply(null, eventArgs);
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "checkedNodes",
                    ["directoryTree", "checkedNodes"],
                    AntdDirectoryTree_Helpers
                  ).apply(null, eventArgs);
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "checkedDetails",
                    ["directoryTree", "checkedDetails"],
                    AntdDirectoryTree_Helpers
                  ).apply(null, eventArgs);
                },
                onExpand: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "expandedKeys",
                    ["directoryTree", "expandedKeys"],
                    AntdDirectoryTree_Helpers
                  ).apply(null, eventArgs);
                },
                onSelect: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "selectedKeys",
                    ["directoryTree", "selectedKeys"],
                    AntdDirectoryTree_Helpers
                  ).apply(null, eventArgs);
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "selectedNodes",
                    ["directoryTree", "selectedNodes"],
                    AntdDirectoryTree_Helpers
                  ).apply(null, eventArgs);
                },
                selectedKeys: generateStateValueProp($state, [
                  "directoryTree",
                  "selectedKeys"
                ]),
                treeData: [
                  {
                    title: "Node 0",
                    key: "0",
                    children: [
                      {
                        title: "Node 0-0",
                        key: "0-0",
                        children: [
                          {
                            title: "Node 0-0-0",
                            key: "0-0-0",
                            disableCheckbox: true
                          },
                          { title: "Node 0-0-1", key: "0-0-1", disabled: true },
                          { title: "Node 0-0-2", key: "0-0-2" }
                        ]
                      },
                      {
                        title: "Node 0-1",
                        key: "0-1",
                        children: [
                          { title: "Node 0-1-0", key: "0-1-0" },
                          { title: "Node 0-1-1", key: "0-1-1" }
                        ]
                      }
                    ]
                  }
                ]
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "checkedKeys",
                    plasmicStateName: "directoryTree.checkedKeys"
                  },
                  {
                    name: "checkedNodes",
                    plasmicStateName: "directoryTree.checkedNodes"
                  },
                  {
                    name: "checkedDetails",
                    plasmicStateName: "directoryTree.checkedDetails"
                  },
                  {
                    name: "selectedKeys",
                    plasmicStateName: "directoryTree.selectedKeys"
                  },
                  {
                    name: "selectedNodes",
                    plasmicStateName: "directoryTree.selectedNodes"
                  },
                  {
                    name: "expandedKeys",
                    plasmicStateName: "directoryTree.expandedKeys"
                  }
                ],
                [],
                AntdDirectoryTree_Helpers ?? {},
                child$Props
              );

              return (
                <AntdDirectoryTree
                  data-plasmic-name={"directoryTree"}
                  data-plasmic-override={overrides.directoryTree}
                  {...child$Props}
                />
              );
            })()}
            <AntdSelect
              data-plasmic-name={"select"}
              data-plasmic-override={overrides.select}
              className={classNames("__wab_instance", sty.select)}
              defaultStylesClassName={classNames(
                projectcss.root_reset,
                projectcss.plasmic_default_styles,
                projectcss.plasmic_mixins,
                styleTokensClassNames
              )}
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["select", "value"]).apply(
                  null,
                  eventArgs
                );
              }}
              options={(() => {
                const __composite = [
                  { type: "option", value: null, label: null },
                  { value: null, label: null, type: "option" },
                  { value: null, label: null, type: null },
                  { type: "option", value: null, label: null }
                ];
                __composite["0"]["value"] = "3";
                __composite["0"]["label"] = "3 Dir Layers";
                __composite["1"]["value"] = "4";
                __composite["1"]["label"] = "4 Dir Layers";
                __composite["2"]["value"] = "5";
                __composite["2"]["label"] = "6 Dir Layers";
                __composite["2"]["type"] = "option";
                __composite["3"]["value"] = "6";
                __composite["3"]["label"] = "6 Dir Layers";
                return __composite;
              })()}
              placeholder={"Select Num of Levels..."}
              popupScopeClassName={sty["select__popup"]}
              value={generateStateValueProp($state, ["select", "value"])}
            />

            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__rsKzz
              )}
              component={Link}
              href={"https://www.plasmic.app/"}
              platform={"nextjs"}
            >
              {"Path: / Global Root / "}
            </PlasmicLink__>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  dashboard: [
    "dashboard",
    "textField",
    "svg",
    "table",
    "directoryTree",
    "select"
  ],
  textField: ["textField"],
  svg: ["svg"],
  table: ["table"],
  directoryTree: ["directoryTree"],
  select: ["select"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  dashboard: "div";
  textField: typeof TextField;
  svg: "svg";
  table: typeof RichTable;
  directoryTree: typeof AntdDirectoryTree;
  select: typeof AntdSelect;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDashboard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDashboard__VariantsArgs;
    args?: PlasmicDashboard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicDashboard__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicDashboard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDashboard__ArgProps,
          internalVariantPropNames: PlasmicDashboard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDashboard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "dashboard") {
    func.displayName = "PlasmicDashboard";
  } else {
    func.displayName = `PlasmicDashboard.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "c8gT28iq7v39gxBJ6CcbGP"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicDashboard = Object.assign(
  // Top-level PlasmicDashboard renders the root element
  withUsePlasmicAuth(makeNodeComponent("dashboard")),
  {
    // Helper components rendering sub-elements
    textField: makeNodeComponent("textField"),
    svg: makeNodeComponent("svg"),
    table: makeNodeComponent("table"),
    directoryTree: makeNodeComponent("directoryTree"),
    select: makeNodeComponent("select"),

    // Metadata about props expected for PlasmicDashboard
    internalVariantProps: PlasmicDashboard__VariantProps,
    internalArgProps: PlasmicDashboard__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Hive Dashboard",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDashboard;
/* prettier-ignore-end */
