/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: c8gT28iq7v39gxBJ6CcbGP

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_2Iv9BlnBGnjW } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 2Iv9blnBGnjW/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_2Iv9BlnBGnjW
});
