# Generated by Django 5.2.7 on 2025-11-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UiHostMap',
            fields=[
                ('host_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('root_dentry', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ui_host_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UiVirtualNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('node_kind', models.CharField(choices=[('virtual', 'Virtual'), ('mount', 'Mount')], max_length=7)),
                ('target_type', models.CharField(choices=[('none', 'None'), ('host', 'Host'), ('dentry', 'Dentry')], default='none', max_length=6)),
                ('target_host', models.CharField(blank=True, max_length=128, null=True)),
                ('target_dentry', models.BigIntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ui_virtual_node',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnifiedTree',
            fields=[
                ('node_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('parent_node_id', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=255)),
                ('node_kind', models.CharField(max_length=32)),
                ('inode_id', models.BigIntegerField(null=True)),
                ('dentry_id', models.BigIntegerField(null=True)),
                ('has_children', models.BooleanField()),
            ],
            options={
                'db_table': 'hive_api.v_unified_tree',
                'managed': False,
            },
        ),
    ]
