# Generated by Django 5.2.7 on 2025-11-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unifiedtree',
            table='v_unified_tree',
        ),
    ]
