/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: c8gT28iq7v39gxBJ6CcbGP
// Component: PylZ-UK7gSPz

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import TextField from "../../TextField"; // plasmic-import: OfVdG6fCBlg2/component
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { TableBrowser } from "@/components/TableBrowser"; // plasmic-import: jVQANZxExoPl/codeComponent
import { TreeBrowser } from "@/components/TreeBrowser"; // plasmic-import: lDT68TVAGwod/codeComponent
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: c8gT28iq7v39gxBJ6CcbGP/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: c8gT28iq7v39gxBJ6CcbGP/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: c8gT28iq7v39gxBJ6CcbGP/projectcss
import sty from "./PlasmicFilesystemConfig.module.css"; // plasmic-import: PylZ-UK7gSPz/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 1y_RXGc1d4jh/icon

createPlasmicElementProxy;

export type PlasmicFilesystemConfig__VariantMembers = {};
export type PlasmicFilesystemConfig__VariantsArgs = {};
type VariantPropType = keyof PlasmicFilesystemConfig__VariantsArgs;
export const PlasmicFilesystemConfig__VariantProps =
  new Array<VariantPropType>();

export type PlasmicFilesystemConfig__ArgsType = {};
type ArgPropType = keyof PlasmicFilesystemConfig__ArgsType;
export const PlasmicFilesystemConfig__ArgProps = new Array<ArgPropType>();

export type PlasmicFilesystemConfig__OverridesType = {
  dashboard?: Flex__<"div">;
  textField?: Flex__<typeof TextField>;
  svg?: Flex__<"svg">;
  tableBrowser?: Flex__<typeof TableBrowser>;
  link?: Flex__<"a"> & Partial<LinkProps>;
  treeBrowser?: Flex__<typeof TreeBrowser>;
};

export interface DefaultFilesystemConfigProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFilesystemConfig__RenderFunc(props: {
  variants: PlasmicFilesystemConfig__VariantsArgs;
  args: PlasmicFilesystemConfig__ArgsType;
  overrides: PlasmicFilesystemConfig__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textField.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicFilesystemConfig.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicFilesystemConfig.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicFilesystemConfig.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"dashboard"}
          data-plasmic-override={overrides.dashboard}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.dashboard
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox___7XcWx)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__tqu9N)}
              displayHeight={"38px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hive_admin/images/image11.svg",
                fullWidth: 150,
                fullHeight: 150,
                aspectRatio: 1
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__rKQy0)}
              displayHeight={"38px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hive_admin/images/image12.svg",
                fullWidth: 150,
                fullHeight: 150,
                aspectRatio: 1
              }}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__apFbP)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__uyofo)}
              displayHeight={"38px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hive_admin/images/image11.svg",
                fullWidth: 150,
                fullHeight: 150,
                aspectRatio: 1
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__hjl0D)}
              displayHeight={"38px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hive_admin/images/image15.svg",
                fullWidth: 150,
                fullHeight: 150,
                aspectRatio: 1
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__kKm5Q)}
              displayHeight={"38px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hive_admin/images/image15.svg",
                fullWidth: 150,
                fullHeight: 150,
                aspectRatio: 1
              }}
            />

            <TextField
              data-plasmic-name={"textField"}
              data-plasmic-override={overrides.textField}
              className={classNames("__wab_instance", sty.textField)}
              inputMode={"search"}
              label={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kz21U
                  )}
                >
                  {"Label"}
                </div>
              }
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["textField", "value"]).apply(
                  null,
                  eventArgs
                );

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Search"}
              type={"search"}
              value={generateStateValueProp($state, ["textField", "value"])}
            />

            <CircleIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />

            <AntdButton
              className={classNames("__wab_instance", sty.button___0Ex9N)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ak21
                )}
              >
                {"Dashboards"}
              </div>
            </AntdButton>
            <AntdButton
              className={classNames("__wab_instance", sty.button__wqkTh)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__h9OZ9
                )}
              >
                {"Actions"}
              </div>
            </AntdButton>
            <AntdButton
              className={classNames("__wab_instance", sty.button__gpy4Q)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__umVcf
                )}
              >
                {"Logs"}
              </div>
            </AntdButton>
            <AntdButton
              className={classNames("__wab_instance", sty.button___6TTuu)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rps2Z
                )}
              >
                {"Reports"}
              </div>
            </AntdButton>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__oRyBh)}>
            <div className={classNames(projectcss.all, sty.freeBox__saB2Q)}>
              <TableBrowser
                data-plasmic-name={"tableBrowser"}
                data-plasmic-override={overrides.tableBrowser}
                baseUrl={"/api/v1/filelist"}
                className={classNames("__wab_instance", sty.tableBrowser)}
                designTimeSample={true}
                enableSearch={false}
                height={"60vh"}
                rowKey={"id"}
              />
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__apTkU)}>
            <PlasmicLink__
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link
              )}
              component={Link}
              href={"https://www.plasmic.app/"}
              platform={"nextjs"}
            >
              {"Path: / Global Root / "}
            </PlasmicLink__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__lg0Jy)}>
            <TreeBrowser
              data-plasmic-name={"treeBrowser"}
              data-plasmic-override={overrides.treeBrowser}
              baseUrl={"/api/v1/tree"}
              className={classNames("__wab_instance", sty.treeBrowser)}
              designTimeSample={true}
              height={"60vh"}
              onSelect={async node => {
                const $steps = {};

                $steps["updateTextFieldValue"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["textField", "value"]
                        },
                        operation: 0
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateTextFieldValue"] != null &&
                  typeof $steps["updateTextFieldValue"] === "object" &&
                  typeof $steps["updateTextFieldValue"].then === "function"
                ) {
                  $steps["updateTextFieldValue"] =
                    await $steps["updateTextFieldValue"];
                }
              }}
              parentParam={"parent"}
              rootParentValue={"root"}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  dashboard: [
    "dashboard",
    "textField",
    "svg",
    "tableBrowser",
    "link",
    "treeBrowser"
  ],
  textField: ["textField"],
  svg: ["svg"],
  tableBrowser: ["tableBrowser"],
  link: ["link"],
  treeBrowser: ["treeBrowser"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  dashboard: "div";
  textField: typeof TextField;
  svg: "svg";
  tableBrowser: typeof TableBrowser;
  link: "a";
  treeBrowser: typeof TreeBrowser;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFilesystemConfig__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFilesystemConfig__VariantsArgs;
    args?: PlasmicFilesystemConfig__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFilesystemConfig__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFilesystemConfig__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFilesystemConfig__ArgProps,
          internalVariantPropNames: PlasmicFilesystemConfig__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFilesystemConfig__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "dashboard") {
    func.displayName = "PlasmicFilesystemConfig";
  } else {
    func.displayName = `PlasmicFilesystemConfig.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "c8gT28iq7v39gxBJ6CcbGP"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicFilesystemConfig = Object.assign(
  // Top-level PlasmicFilesystemConfig renders the root element
  withUsePlasmicAuth(makeNodeComponent("dashboard")),
  {
    // Helper components rendering sub-elements
    textField: makeNodeComponent("textField"),
    svg: makeNodeComponent("svg"),
    tableBrowser: makeNodeComponent("tableBrowser"),
    link: makeNodeComponent("link"),
    treeBrowser: makeNodeComponent("treeBrowser"),

    // Metadata about props expected for PlasmicFilesystemConfig
    internalVariantProps: PlasmicFilesystemConfig__VariantProps,
    internalArgProps: PlasmicFilesystemConfig__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Hive FS Config",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicFilesystemConfig;
/* prettier-ignore-end */
