import { useEffect, useMemo, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../../../ui/card';
import { Input } from '../../../ui/input';
import { Label } from '../../../ui/label';
import { Button } from '../../../ui/button';
import { Separator } from '../../../ui/separator';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../../ui/select';
import { Badge } from '../../../ui/badge';
import {
  History,
  Bell,
  AlertTriangle,
  Search,
  Download,
  ChevronDown,
  ChevronRight,
  Check,
  Clock,
  XCircle,
  Mail,
  Users,
  Radio as RadioIcon,
  MessageSquare,
  Smartphone,
  AlertCircle,
  CheckCircle,
  Info,
  Filter,
} from 'lucide-react';

const pastelPalette = ['#FFE4F3', '#FFF6E3', '#E7F5FF', '#E8FFFB', '#F2E8FF', '#FFF0EE', '#E6FFF2', '#F8F5FF'];
const API_BASE = import.meta?.env?.VITE_NODES_API_BASE_URL ?? 'http://localhost:8000/api/v1';

const hashString = (value: string) =>
  value.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);

const getPastelColor = (key: string) => pastelPalette[hashString(key) % pastelPalette.length];

interface NotificationHistoryItem {
  id: string;
  type: 'notification' | 'alert';
  name: string;
  description: string;
  severity?: 'critical' | 'high' | 'medium' | 'low';
  category?: string;
  status: 'new' | 'acknowledged' | 'in-progress' | 'resolved' | 'closed' | 'sent';
  timestamp: string;
  triggeredBy: string;
  endpoints: {
    name: string;
    type: string;
    status: 'sent' | 'failed' | 'pending';
  }[];
  message: string;
  acknowledgedBy?: string;
  acknowledgedAt?: string;
  resolvedBy?: string;
  resolvedAt?: string;
  closedBy?: string;
  closedAt?: string;
}

const normalizeApiList = (payload: unknown): any[] => {
  if (Array.isArray(payload)) return payload;
  if (payload && Array.isArray((payload as any).results)) return (payload as any).results;
  return [];
};

const normalizeSeverity = (value: unknown): NotificationHistoryItem['severity'] | undefined => {
  if (typeof value !== 'string') return undefined;
  const normalized = value.toLowerCase();
  if (['critical', 'high', 'medium', 'low'].includes(normalized)) {
    return normalized as NotificationHistoryItem['severity'];
  }
  return undefined;
};

const normalizeEndpointStatus = (value: unknown): 'sent' | 'failed' | 'pending' => {
  if (typeof value !== 'string') return 'sent';
  const normalized = value.toLowerCase();
  if (normalized === 'failed' || normalized === 'pending') return normalized;
  return 'sent';
};

const mapWorkflowToUiStatus = (
  wStatus?: string | null,
  fallbackStatus?: string | null,
  target?: 'notification' | 'alert'
): NotificationHistoryItem['status'] => {
  const normalizedWorkflow = (wStatus ?? '').toLowerCase();
  switch (normalizedWorkflow) {
    case 'new':
      return 'new';
    case 'acknowledged':
      return 'acknowledged';
    case 'working':
      return 'in-progress';
    case 'resolved':
      return 'resolved';
    case 'closed':
      return 'closed';
    default:
      break;
  }

  const normalizedFallback = (fallbackStatus ?? '').toLowerCase();
  if (normalizedFallback === 'sent') return 'sent';
  if (normalizedFallback === 'resolved') return 'resolved';
  if (normalizedFallback === 'acknowledged') return 'acknowledged';
  if (normalizedFallback === 'triggered') return 'new';
  if (normalizedFallback === 'suppressed') return 'closed';

  return target === 'notification' ? 'sent' : 'in-progress';
};

const mapNotificationRecord = (record: any): NotificationHistoryItem => {
  const timestamp =
    record?.updated_at || record?.created_at || record?.next_attempt_at || new Date().toISOString();
  const payload = (record && record.payload && typeof record.payload === 'object'
    ? record.payload
    : null) as Record<string, any> | null;
  const endpointsPayload =
    payload && Array.isArray(payload.endpoints)
      ? payload.endpoints
      : payload && Array.isArray(payload.targets)
        ? payload.targets
        : [];

  const endpoints =
    endpointsPayload.length > 0
      ? endpointsPayload.map((endpoint: any) => ({
          name:
            endpoint?.name ??
            endpoint?.target_name ??
            endpoint?.destination ??
            endpoint?.destination_email ??
            'Endpoint',
          type: endpoint?.type ?? endpoint?.channel ?? endpoint?.delivery_channel ?? 'email',
          status: normalizeEndpointStatus(endpoint?.status),
        }))
      : [];

  return {
    id: String(record?.notification_id ?? record?.id ?? timestamp),
    type: 'notification',
    name: record?.subject ?? 'Notification',
    description:
      (payload && (payload.description ?? payload.summary)) ??
      record?.subject ??
      'Notification generated by HiveFS',
    severity: normalizeSeverity(payload?.severity ?? record?.priority),
    category: payload?.category,
    status: mapWorkflowToUiStatus(record?.w_status, record?.status, 'notification'),
    timestamp,
    triggeredBy: payload?.triggered_by ?? record?.notification_type ?? 'Notification Scheduler',
    endpoints,
    message:
      record?.body ??
      payload?.message ??
      payload?.details ??
      'No message provided for this notification.',
    acknowledgedBy: payload?.acknowledged_by,
    acknowledgedAt: payload?.acknowledged_at,
    resolvedBy: payload?.resolved_by,
    resolvedAt: payload?.resolved_at,
    closedBy: payload?.closed_by,
    closedAt: payload?.closed_at,
  };
};

const mapAlertRecord = (record: any): NotificationHistoryItem => {
  const timestamp =
    record?.updated_at || record?.triggered_at || record?.created_at || new Date().toISOString();
  const metadata =
    record && record.metadata && typeof record.metadata === 'object'
      ? (record.metadata as Record<string, any>)
      : {};

  return {
    id: String(record?.alert_id ?? record?.id ?? timestamp),
    type: 'alert',
    name: record?.title ?? record?.source ?? 'Alert',
    description: record?.message ?? 'Alert generated by HiveFS monitor',
    severity: normalizeSeverity(record?.severity),
    status: mapWorkflowToUiStatus(record?.w_status, record?.status, 'alert'),
    timestamp,
    triggeredBy: record?.source ?? 'Alert Engine',
    endpoints: [],
    message: record?.message ?? '',
    acknowledgedBy: record?.acknowledged_by ?? metadata?.acknowledged_by,
    acknowledgedAt: record?.acknowledged_at ?? metadata?.acknowledged_at,
    resolvedBy: metadata?.resolved_by,
    resolvedAt: record?.resolved_at ?? metadata?.resolved_at,
    closedBy: metadata?.closed_by,
    closedAt: metadata?.closed_at,
  };
};

const mapFilterStatusToParams = (
  filterStatus: string,
  target: 'notification' | 'alert'
): { status?: string; w_status?: string } => {
  if (filterStatus === 'all') return {};
  if (filterStatus === 'sent' && target === 'notification') {
    return { status: 'sent' };
  }

  const workflowMap: Record<string, string> = {
    new: 'new',
    acknowledged: 'acknowledged',
    'in-progress': 'working',
    resolved: 'resolved',
    closed: 'closed',
  };

  const mapped = workflowMap[filterStatus];
  if (mapped) {
    return { w_status: mapped };
  }
  return {};
};

const getTimeRangeMs = (value: string): number | null => {
  switch (value) {
    case '24h':
      return 24 * 60 * 60 * 1000;
    case '3d':
      return 3 * 24 * 60 * 60 * 1000;
    case '7d':
      return 7 * 24 * 60 * 60 * 1000;
    case '30d':
      return 30 * 24 * 60 * 60 * 1000;
    case 'all':
    default:
      return null;
  }
};

export function NotificationsHistoryTab() {
  const [filterType, setFilterType] = useState<string>('all');
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [filterSeverity, setFilterSeverity] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedItems, setExpandedItems] = useState<string[]>([]);

  // Mock history data
  const [historyItems, setHistoryItems] = useState<NotificationHistoryItem[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [filterTimeRange, setFilterTimeRange] = useState<string>('7d');

  const getSeverityColor = (severity?: string) => {
    switch (severity) {
      case 'critical':
        return 'bg-red-400';
      case 'high':
        return 'bg-orange-300';
      case 'medium':
        return 'bg-yellow-200';
      case 'low':
        return 'bg-emerald-200';
      default:
        return 'bg-slate-200';
    }
  };

  const getStatusBadge = (item: NotificationHistoryItem) => {
    if (item.type === 'notification') {
      return (
        <Badge variant="outline" className="text-xs">
          <CheckCircle className="w-3 h-3 mr-1" />
          Sent
        </Badge>
      );
    }

    // Alert statuses
    switch (item.status) {
      case 'new':
        return (
          <Badge variant="destructive" className="text-xs">
            <AlertCircle className="w-3 h-3 mr-1" />
            New
          </Badge>
        );
      case 'acknowledged':
        return (
          <Badge variant="default" className="text-xs bg-blue-500">
            <Check className="w-3 h-3 mr-1" />
            Acknowledged
          </Badge>
        );
      case 'in-progress':
        return (
          <Badge variant="default" className="text-xs bg-purple-500">
            <Clock className="w-3 h-3 mr-1" />
            In Progress
          </Badge>
        );
      case 'resolved':
        return (
          <Badge variant="default" className="text-xs bg-green-500">
            <CheckCircle className="w-3 h-3 mr-1" />
            Resolved
          </Badge>
        );
      case 'closed':
        return (
          <Badge variant="outline" className="text-xs">
            <XCircle className="w-3 h-3 mr-1" />
            Closed
          </Badge>
        );
      default:
        return null;
    }
  };

  const getEndpointIcon = (type: string) => {
    switch (type) {
      case 'email':
        return <Mail className="w-3 h-3" />;
      case 'email-group':
        return <Users className="w-3 h-3" />;
      case 'snmp':
        return <RadioIcon className="w-3 h-3" />;
      case 'pagerduty':
        return <AlertCircle className="w-3 h-3" />;
      case 'slack':
      case 'teams':
        return <MessageSquare className="w-3 h-3" />;
      case 'sms':
        return <Smartphone className="w-3 h-3" />;
      default:
        return <Bell className="w-3 h-3" />;
    }
  };

  const toggleExpanded = (id: string) => {
    setExpandedItems((prev) =>
      prev.includes(id) ? prev.filter((itemId) => itemId !== id) : [...prev, id]
    );
  };

  const handleAcknowledge = (id: string) => {
    console.log('Acknowledging alert:', id);
    // Would update the alert status to acknowledged
  };

  const handleResolve = (id: string) => {
    console.log('Resolving alert:', id);
    // Would update the alert status to resolved
  };

  const handleClose = (id: string) => {
    console.log('Closing alert:', id);
    // Would update the alert status to closed
  };

  const handleSetInProgress = (id: string) => {
    console.log('Setting alert to in-progress:', id);
    // Would update the alert status to in-progress
  };

  const formatTimestamp = (timestamp: string) => {
    const date = new Date(timestamp);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const minutes = Math.floor(diff / 60000);
    const hours = Math.floor(diff / 3600000);
    const days = Math.floor(diff / 86400000);

    if (minutes < 1) return 'Just now';
    if (minutes < 60) return `${minutes}m ago`;
    if (hours < 24) return `${hours}h ago`;
    if (days < 7) return `${days}d ago`;

    return date.toLocaleString();
  };

  useEffect(() => {
    const abortController = new AbortController();
    const loadHistory = async () => {
      setIsLoading(true);
      setFetchError(null);

      const targets =
        filterType === 'all'
          ? (['notification', 'alert'] as Array<'notification' | 'alert'>)
          : ([filterType] as Array<'notification' | 'alert'>);

      try {
        const allItems: NotificationHistoryItem[] = [];

        await Promise.all(
          targets.map(async (target) => {
            const params = new URLSearchParams({ limit: '200' });
            const mapped = mapFilterStatusToParams(filterStatus, target);
            if (mapped.status) params.append('status', mapped.status);
            if (mapped.w_status) params.append('w_status', mapped.w_status);

            const endpoint = target === 'alert' ? 'alerts' : 'notifications';
            const response = await fetch(`${API_BASE}/${endpoint}?${params.toString()}`, {
              signal: abortController.signal,
            });
            if (!response.ok) {
              throw new Error(`Failed to load ${endpoint} (${response.status})`);
            }
            const payload = await response.json();
            const records = normalizeApiList(payload);
            const mappedItems =
              target === 'alert'
                ? records.map(mapAlertRecord)
                : records.map(mapNotificationRecord);
            allItems.push(...mappedItems);
          })
        );

        if (!abortController.signal.aborted) {
          setHistoryItems(allItems);
        }
      } catch (err) {
        if (abortController.signal.aborted) return;
        setFetchError(err instanceof Error ? err.message : 'Unable to load history');
        setHistoryItems([]);
      } finally {
        if (!abortController.signal.aborted) {
          setIsLoading(false);
        }
      }
    };

    loadHistory();
    return () => abortController.abort();
  }, [filterType, filterStatus]);

  const filteredItems = useMemo(() => {
    const rangeMs = getTimeRangeMs(filterTimeRange);
    const now = Date.now();
    return historyItems.filter((item) => {
      if (filterType !== 'all' && item.type !== filterType) return false;
      if (filterStatus !== 'all' && item.status !== filterStatus) return false;
      if (filterSeverity !== 'all' && item.severity !== filterSeverity) return false;
      if (searchQuery && !item.name.toLowerCase().includes(searchQuery.toLowerCase())) return false;
      if (rangeMs !== null) {
        const timestampValue = new Date(item.timestamp).getTime();
        if (Number.isFinite(timestampValue) && now - timestampValue > rangeMs) return false;
      }
      return true;
    });
  }, [historyItems, filterType, filterStatus, filterSeverity, searchQuery, filterTimeRange]);

  const handleExportCsv = () => {
    if (!filteredItems.length) return;
    const headers = [
      'ID',
      'Type',
      'Name',
      'Description',
      'Severity',
      'Status',
      'Timestamp',
      'Triggered By',
      'Message',
      'Endpoints',
    ];

    const rows = filteredItems.map((item) => [
      item.id,
      item.type,
      item.name,
      item.description ?? '',
      item.severity ?? '',
      item.status,
      item.timestamp,
      item.triggeredBy,
      item.message.replace(/\n/g, ' '),
      item.endpoints
        .map((endpoint) => `${endpoint.name} (${endpoint.type}) - ${endpoint.status}`)
        .join('; '),
    ]);

    const csv = [headers, ...rows]
      .map((row) =>
        row
          .map((value) => `"${String(value ?? '').replace(/"/g, '""')}"`)
          .join(',')
      )
      .join('\n');

    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `notifications_history_${new Date().toISOString()}.csv`);
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex h-full w-full flex-col gap-6 overflow-auto bg-gradient-to-br from-background via-primary/5 to-background p-8">
      {/* Page Header */}
      <div>
        <h1 className="text-foreground/80">Notification History</h1>
        <p className="text-muted-foreground text-sm mt-1">Notifications - By filtered values</p>
      </div>

      {/* Filters Card */}
      <Card className="border-primary/10 bg-gradient-to-b from-background/80 to-background shadow-lg shadow-primary/10">
        <CardHeader>
          <CardTitle className="text-foreground/90 flex items-center gap-2">
            <Filter className="w-5 h-5" />
            Filters
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-nowrap gap-2 overflow-x-auto pb-2 whitespace-nowrap">
            <div className="w-36 flex-none">
              <Label htmlFor="filter-type" className="text-xs text-muted-foreground">
                Type
              </Label>
              <Select value={filterType} onValueChange={setFilterType}>
                <SelectTrigger id="filter-type" className="mt-1 text-sm h-8">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Types</SelectItem>
                  <SelectItem value="alert">
                    <div className="flex items-center gap-2">
                      <AlertTriangle className="w-4 h-4" />
                      Alerts Only
                    </div>
                  </SelectItem>
                  <SelectItem value="notification">
                    <div className="flex items-center gap-2">
                      <Bell className="w-4 h-4" />
                      Notifications Only
                    </div>
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="w-36 flex-none">
              <Label htmlFor="filter-status" className="text-xs text-muted-foreground">
                Status
              </Label>
              <Select value={filterStatus} onValueChange={setFilterStatus}>
                <SelectTrigger id="filter-status" className="mt-1 text-sm h-8">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Statuses</SelectItem>
                  <SelectItem value="new">New</SelectItem>
                  <SelectItem value="acknowledged">Acknowledged</SelectItem>
                  <SelectItem value="in-progress">In Progress</SelectItem>
                  <SelectItem value="resolved">Resolved</SelectItem>
                  <SelectItem value="closed">Closed</SelectItem>
                  <SelectItem value="sent">Sent (Notifications)</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="w-36 flex-none">
              <Label htmlFor="filter-severity" className="text-xs text-muted-foreground">
                Severity
              </Label>
              <Select value={filterSeverity} onValueChange={setFilterSeverity}>
                <SelectTrigger id="filter-severity" className="mt-1 text-sm h-8">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Severities</SelectItem>
                  <SelectItem value="critical">Critical</SelectItem>
                  <SelectItem value="high">High</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="low">Low</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="w-36 flex-none">
              <Label htmlFor="filter-time" className="text-xs text-muted-foreground">
                Time Range
              </Label>
              <Select value={filterTimeRange} onValueChange={setFilterTimeRange}>
                <SelectTrigger id="filter-time" className="mt-1 text-sm h-8">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="24h">Last 24 Hours</SelectItem>
                  <SelectItem value="3d">Last 3 Days</SelectItem>
                  <SelectItem value="7d">Last 7 Days</SelectItem>
                  <SelectItem value="30d">Last 30 Days</SelectItem>
                  <SelectItem value="all">All Time</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="w-48 flex-none">
              <Label htmlFor="search" className="text-xs text-muted-foreground">
                Search
              </Label>
              <div className="relative mt-1">
                <Search className="absolute left-2 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <Input
                  id="search"
                  placeholder="Search by name..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-8 text-sm h-8"
                />
              </div>
            </div>
          </div>

          <div className="flex items-center justify-between mt-4">
            <p className="text-xs text-muted-foreground">
              Showing {filteredItems.length} of {historyItems.length} items
            </p>
            <Button
              size="sm"
              variant="outline"
              className="text-xs h-7"
              onClick={handleExportCsv}
              disabled={!filteredItems.length}
            >
              <Download className="w-3 h-3 mr-1" />
              Export to CSV
            </Button>
          </div>

          {fetchError && (
            <div className="mt-3 rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">
              {fetchError}
            </div>
          )}
        </CardContent>
      </Card>

      {/* History Items */}
      <Card className="border-primary/10 bg-gradient-to-b from-background/80 to-background shadow-lg shadow-primary/10">
        <CardHeader>
          <CardTitle className="text-foreground/90 flex items-center gap-2">
            <History className="w-5 h-5" />
            History ({filteredItems.length})
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-2">
            {isLoading && (
              <div className="text-center py-8 text-muted-foreground text-sm">Loading history…</div>
            )}

            {filteredItems.map((item) => {
              const isExpanded = expandedItems.includes(item.id);
              const pastelColor = getPastelColor(item.id);

              return (
                <div
                  key={item.id}
                  className="border rounded-lg transition-all shadow-sm"
                  style={{
                    backgroundColor: pastelColor,
                    borderColor: pastelColor,
                    color: '#0f172a',
                  }}
                >
                  {/* Summary Row */}
                  <div className="p-3 flex items-center justify-between">
                    <div className="flex items-center gap-3 flex-1">
                      <Button
                        size="sm"
                        variant="ghost"
                        className="h-6 w-6 p-0"
                        onClick={() => toggleExpanded(item.id)}
                      >
                        {isExpanded ? (
                          <ChevronDown className="w-4 h-4 text-slate-800" />
                        ) : (
                          <ChevronRight className="w-4 h-4 text-slate-800" />
                        )}
                      </Button>

                      {item.type === 'alert' ? (
                        <AlertTriangle className="w-5 h-5 text-orange-600" />
                      ) : (
                        <Bell className="w-5 h-5 text-sky-600" />
                      )}

                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <p className="text-sm font-medium text-foreground/90">{item.name}</p>
                          {item.severity && (
                            <div
                              className={`w-2 h-2 rounded-full ${getSeverityColor(
                                item.severity
                              )}`}
                              title={item.severity}
                            />
                          )}
                        </div>
                        <p className="text-xs text-muted-foreground">{item.description}</p>
                      </div>

                      <div className="text-xs text-muted-foreground">
                        {formatTimestamp(item.timestamp)}
                      </div>

                      {getStatusBadge(item)}
                    </div>
                  </div>

                  {/* Expanded Details */}
                  {isExpanded && (
                    <>
                      <Separator />
                      <div className="p-4 space-y-4 bg-background/50">
                        {/* Message */}
                        <div>
                          <p className="text-xs text-muted-foreground mb-1">Message</p>
                          <p className="text-sm bg-muted/50 rounded p-2 border border-border">
                            {item.message}
                          </p>
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                          {/* Trigger Info */}
                          <div>
                            <p className="text-xs text-muted-foreground mb-1">Triggered By</p>
                            <p className="text-sm">{item.triggeredBy}</p>
                            <p className="text-xs text-muted-foreground mt-1">
                              {new Date(item.timestamp).toLocaleString()}
                            </p>
                          </div>

                          {/* Endpoints */}
                          <div>
                            <p className="text-xs text-muted-foreground mb-1">
                              Endpoints ({item.endpoints.length})
                            </p>
                            <div className="space-y-1">
                              {item.endpoints.map((endpoint, idx) => (
                                <div
                                  key={idx}
                                  className="flex items-center gap-2 text-xs bg-muted/30 rounded px-2 py-1"
                                >
                                  {getEndpointIcon(endpoint.type)}
                                  <span className="flex-1">{endpoint.name}</span>
                                  {endpoint.status === 'sent' ? (
                                    <Check className="w-3 h-3 text-green-500" />
                                  ) : endpoint.status === 'failed' ? (
                                    <XCircle className="w-3 h-3 text-red-500" />
                                  ) : (
                                    <Clock className="w-3 h-3 text-yellow-500" />
                                  )}
                                </div>
                              ))}
                            </div>
                          </div>
                        </div>

                        {/* Alert-specific timeline */}
                        {item.type === 'alert' && (
                          <div>
                            <p className="text-xs text-muted-foreground mb-2">Alert Timeline</p>
                            <div className="space-y-2">
                              <div className="flex items-start gap-2 text-xs">
                                <div className="w-2 h-2 rounded-full bg-red-500 mt-1" />
                                <div className="flex-1">
                                  <p className="text-foreground/90">Alert triggered</p>
                                  <p className="text-muted-foreground">
                                    {new Date(item.timestamp).toLocaleString()}
                                  </p>
                                </div>
                              </div>

                              {item.acknowledgedAt && (
                                <div className="flex items-start gap-2 text-xs">
                                  <div className="w-2 h-2 rounded-full bg-blue-500 mt-1" />
                                  <div className="flex-1">
                                    <p className="text-foreground/90">
                                      Acknowledged by {item.acknowledgedBy}
                                    </p>
                                    <p className="text-muted-foreground">
                                      {new Date(item.acknowledgedAt).toLocaleString()}
                                    </p>
                                  </div>
                                </div>
                              )}

                              {item.resolvedAt && (
                                <div className="flex items-start gap-2 text-xs">
                                  <div className="w-2 h-2 rounded-full bg-green-500 mt-1" />
                                  <div className="flex-1">
                                    <p className="text-foreground/90">
                                      Resolved by {item.resolvedBy}
                                    </p>
                                    <p className="text-muted-foreground">
                                      {new Date(item.resolvedAt).toLocaleString()}
                                    </p>
                                  </div>
                                </div>
                              )}

                              {item.closedAt && (
                                <div className="flex items-start gap-2 text-xs">
                                  <div className="w-2 h-2 rounded-full bg-gray-500 mt-1" />
                                  <div className="flex-1">
                                    <p className="text-foreground/90">
                                      Closed by {item.closedBy}
                                    </p>
                                    <p className="text-muted-foreground">
                                      {new Date(item.closedAt).toLocaleString()}
                                    </p>
                                  </div>
                                </div>
                              )}
                            </div>
                          </div>
                        )}

                        {/* Alert Actions */}
                        {item.type === 'alert' && item.status !== 'closed' && (
                          <>
                            <Separator />
                            <div className="flex gap-2">
                              {item.status === 'new' && (
                                <>
                                  <Button
                                    size="sm"
                                    variant="outline"
                                    className="text-xs h-7"
                                    onClick={() => handleAcknowledge(item.id)}
                                  >
                                    <Check className="w-3 h-3 mr-1" />
                                    Acknowledge
                                  </Button>
                                  <Button
                                    size="sm"
                                    variant="outline"
                                    className="text-xs h-7"
                                    onClick={() => handleSetInProgress(item.id)}
                                  >
                                    <Clock className="w-3 h-3 mr-1" />
                                    Set In Progress
                                  </Button>
                                </>
                              )}

                              {(item.status === 'acknowledged' || item.status === 'in-progress') && (
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="text-xs h-7"
                                  onClick={() => handleResolve(item.id)}
                                >
                                  <CheckCircle className="w-3 h-3 mr-1" />
                                  Resolve
                                </Button>
                              )}

                              {item.status === 'resolved' && (
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="text-xs h-7"
                                  onClick={() => handleClose(item.id)}
                                >
                                  <XCircle className="w-3 h-3 mr-1" />
                                  Close
                                </Button>
                              )}
                            </div>
                          </>
                        )}

                        {/* Audit Note */}
                        {item.type === 'notification' && (
                          <p
                            className="text-muted-foreground opacity-60"
                            style={{ fontSize: '0.7rem', lineHeight: '1.3' }}
                          >
                            Notifications are retained for audit purposes and cannot be deleted
                          </p>
                        )}
                      </div>
                    </>
                  )}
                </div>
              );
            })}

            {!isLoading && filteredItems.length === 0 && (
              <div className="text-center py-12 text-muted-foreground">
                <History className="w-12 h-12 mx-auto mb-3 opacity-50" />
                <p className="text-sm">No notifications or alerts found</p>
                <p className="text-xs mt-1">Try adjusting your filters</p>
              </div>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
