# Generated by Django 5.2.7 on 2026-01-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_uri', models.CharField(blank=True, max_length=1000)),
                ('port', models.IntegerField()),
                ('tls_mode', models.IntegerField()),
                ('tls_verify', models.BooleanField(default=False)),
                ('connect_timeout', models.IntegerField(default=3000)),
                ('bind_method', models.IntegerField(default=False)),
                ('bind_dn', models.CharField(blank=True, max_length=200)),
                ('dn_or_oldap', models.BooleanField(default=True)),
                ('user_dn', models.CharField(blank=True, max_length=200)),
                ('group_dn', models.CharField(blank=True, max_length=200, null=True)),
                ('auth_source', models.CharField(blank=True, max_length=50)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_method', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'LDAP Configuration',
                'verbose_name_plural': 'LDAP Configurations',
            },
        ),
        migrations.CreateModel(
            name='SAMLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idp_entity_id', models.CharField(blank=True, max_length=1000)),
                ('sso_url', models.CharField(blank=True, max_length=1000)),
                ('slo_url', models.CharField(blank=True, max_length=1000)),
                ('certificate', models.TextField(blank=True)),
                ('attribute_mapping', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SAML Configuration',
                'verbose_name_plural': 'SAML Configurations',
            },
        ),
        migrations.CreateModel(
            name='MFAModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('method', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Setting',
                'verbose_name_plural': 'MFA Settings',
            },
        ),
    ]
