# Generated by Django 5.2.7 on 2025-12-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='storage_node_stats',
            table='v_stats',
        ),
    ]
