# Generated by Django 5.2.7 on 2025-12-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage_Node_Stats',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_ts', models.DateTimeField()),
                ('cpu', models.IntegerField(null=True)),
                ('read_iops', models.IntegerField(null=True)),
                ('write_iops', models.IntegerField(null=True)),
                ('total_iops', models.IntegerField(null=True)),
                ('t_throughput', models.IntegerField(null=True)),
                ('c_net_in', models.IntegerField(null=True)),
                ('c_net_out', models.IntegerField(null=True)),
                ('s_net_in', models.IntegerField(null=True)),
                ('s_net_out', models.IntegerField(null=True)),
                ('avg_latency', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'v_sn_stats',
                'managed': False,
            },
        ),
    ]
